game:	Game.java
	javac Game.java

brick:	Brick.java
	javac Brick.java

board: Board.java
	javac Board.java

bundle: *.class *.java Manifest.txt
	jar cfm classproj.jar Manifest.txt *.class *.java README.txt
